config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'
  post 'welcome/all_values_today'
  post 'welcome/test_values'
  get 'welcome/get_indicator/:id' => 'welcome#get_indicator', :as => 'welcome_get_indicator'
  get 'welcome/search/:id/:start_date/:final_date' => 'welcome#search', :as => 'welcome_search'
  get 'welcome/predict/:id' => 'welcome#predict', :as => 'welcome_predict'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NursoftTest</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="content">
      <div class="container">

        <div class="row">
          <div class="col-lg-10 col-md-12 col-lg-offset-1 col-sm-12 titulo">
            <div class="card-box">
              <div class="text-center">
                <h2 class="p-t-10 m-b-0">Nursoft</h2>
                <p class="text-muted">Prueba Técnica</p>
              </div>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-lg-5 col-md-6 col-lg-offset-1">
            <div class="card-box widget-user">
              <div>
                <div class="wid-u-info">
                  <h4 class="m-t-0 m-b-5 font-600">Datos De Prueba</h4>
                  <p class="text-muted m-b-5 font-13">Con esta opción carga por primera vez los datos de prueba.</p>
                  <small class="text-warning">
                    <b><%= link_to 'Obtener Datos', welcome_test_values_path, :method => :post %></b>
                  </small>
                </div>
              </div>
            </div>
          </div>

          <div class="col-lg-5 col-md-6">
            <div class="card-box widget-user">
              <div>
                <div class="wid-u-info">
                  <h4 class="m-t-0 m-b-5 font-600">Datos de hoy</h4>
                  <p class="text-muted m-b-5 font-13">Obten los valores del dia actual</p>
                  <small class="text-custom">
                    <b><%= link_to 'Obtener Datos', welcome_all_values_today_path, :method => :post %></b>
                  </small>
                </div>
              </div>
            </div>
          </div>
        </div>

        <%= yield %>
      </div>
    </div>
  </body>
</html>